In [1]:
from sklearn.svm import SVC
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()
x_train = iris["data"]  # petal length, petal width
y_train = iris["target"]

In [2]:
# SVM Classifier model
svm_clf = SVC(kernel="linear", C=0.1)
svm_clf.fit(x_train, y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [3]:
n_plane=svm_clf.coef_.shape[0]
for i in range(n_plane):
    w = svm_clf.coef_[i]
    b = svm_clf.intercept_[i]
    print(w)
    print(b)

[-0.13001521  0.34590107 -0.74649785 -0.34757868]
1.86433801451
[-0.05500037  0.15500012 -0.51426527 -0.23789395]
1.76185604081
[ 0.092721    0.19757367 -1.24100522 -0.98857889]
6.6107273455


In [4]:
from sklearn.svm import LinearSVC
linear_svm=LinearSVC(C=0.1)
linear_svm.fit(x_train, y_train)


LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [5]:
n_plane=svm_clf.coef_.shape[0]
for i in range(n_plane):
    w = svm_clf.coef_[i]
    b = svm_clf.intercept_[i]
    print(w)
    print(b)

[-0.13001521  0.34590107 -0.74649785 -0.34757868]
1.86433801451
[-0.05500037  0.15500012 -0.51426527 -0.23789395]
1.76185604081
[ 0.092721    0.19757367 -1.24100522 -0.98857889]
6.6107273455
