In [10]:
import tensorflow as tf
a=tf.random_normal((3,2))
b=tf.random_normal((2,3))
c = tf.matmul(a, b)
d = tf.matrix_inverse(c)  
with tf.Session() as ss:
        print('A= ', ss.run(a))
        print('B = ', ss.run(b))
        print('C = ', ss.run(c))
        print('D = ', ss.run(d))

A=  [[ 0.78761029  0.16937575]
 [ 1.48729217  0.00201405]
 [-0.1699851   1.22847939]]
B =  [[ 0.48951098 -0.13445437 -0.54059583]
 [ 0.58346707 -0.45282748 -0.23555098]]
C =  [[-0.52697051  0.35408434 -0.679353  ]
 [-0.58710444 -0.86730123 -1.15829825]
 [-0.25488913  0.0812398  -0.35723546]]
D =  [[  5551674.5       792147.8125   7429041.5   ]
 [ -8608083.      -1228259.125  -11519012.    ]
 [ 38209544.       5451980.5     51130564.    ]]


In [34]:
x = tf.placeholder(tf.float32,shape=[1, 2])
v = tf.Variable([[0.5, 1.0]])
y = 1 / (1 + tf.exp(tf.matmul(tf.negative(x), tf.transpose(v))))
values = ([[1, 2]], [[2, 3]], [[3, 1]])
with tf.Session() as ss:
    ss.run(tf.global_variables_initializer())
    for va in values:
         print(ss.run(y, feed_dict={x:va}))


[[ 0.92414182]]
[[ 0.98201376]]
[[ 0.92414182]]
